name: nibol-test

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: nibol-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./data/raw:/var/opt/mssql/import:ro

volumes:
  sqlserver_data:
